// @ts-nocheck
import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import nodemailer from "npm:nodemailer@6.9.15";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

type SendReportPayload = {
  to: string;
  reportType: string;
  startDate: string;
  endDate: string;
  detailMode: string;
  format: string;
  column: string;
  attachment?: {
    fileName: string;
    mimeType: string;
    contentBase64: string;
  };
};

const requiredEnv = [
  "SMTP_HOST",
  "SMTP_PORT",
  "SMTP_USER",
  "SMTP_PASS",
  "SMTP_FROM",
] as const;

function getMissingEnv() {
  return requiredEnv.filter((key) => !Deno.env.get(key));
}

function badRequest(message: string, status = 400) {
  return new Response(JSON.stringify({ error: message }), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function decodeBase64ToBytes(value: string) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return badRequest("Method not allowed.", 405);
  }

  const missingEnv = getMissingEnv();
  if (missingEnv.length) {
    return badRequest(`Missing SMTP environment variables: ${missingEnv.join(", ")}`, 500);
  }

  let payload: SendReportPayload;
  try {
    payload = (await req.json()) as SendReportPayload;
  } catch {
    return badRequest("Invalid JSON payload.");
  }

  if (!payload?.to || !payload?.reportType || !payload?.startDate || !payload?.endDate) {
    return badRequest("Missing required report fields.");
  }

  if (!payload.attachment?.fileName || !payload.attachment?.mimeType || !payload.attachment?.contentBase64) {
    return badRequest("Missing attachment payload.");
  }

  const smtpHost = Deno.env.get("SMTP_HOST")!;
  const smtpPort = Number(Deno.env.get("SMTP_PORT"));
  const smtpUser = Deno.env.get("SMTP_USER")!;
  const smtpPass = Deno.env.get("SMTP_PASS")!;
  const smtpFrom = Deno.env.get("SMTP_FROM")!;
  const smtpSecure = Deno.env.get("SMTP_SECURE") === "true" || smtpPort === 465;

  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpSecure,
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });

  const subject = `CAPSTONE Report - ${payload.reportType}`;
  const textBody = [
    "Your report request has been submitted.",
    "",
    `Report Type: ${payload.reportType}`,
    `Start Date: ${payload.startDate}`,
    `End Date: ${payload.endDate}`,
    `Detail Mode: ${payload.detailMode}`,
    `Format: ${String(payload.format || "").toUpperCase()}`,
    `Column: ${payload.column || "All"}`,
    "",
    "Generated by CAPSTONE Admin Dashboard",
  ].join("\n");

  const htmlBody = `
    <div style="margin:0;padding:24px;background:#f5f7fb;font-family:Arial,sans-serif;color:#0f172a;">
      <div style="max-width:680px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:16px;overflow:hidden;box-shadow:0 14px 32px rgba(15,23,42,0.12);">
        <div style="padding:18px 22px;background:linear-gradient(135deg,#ff0000 0%,#800000 100%);color:#ffffff;">
          <h2 style="margin:0;font-size:20px;line-height:1.2;">CAPSTONE Report</h2>
          <p style="margin:6px 0 0;font-size:13px;opacity:.95;">Attached is the requested report file.</p>
        </div>
        <div style="padding:18px 22px;">
          <p style="margin:0 0 12px;font-size:14px;color:#334155;">Report details:</p>
          <table style="border-collapse:collapse;width:100%;font-size:14px;">
            <tr><td style="padding:8px 6px;color:#64748b;font-weight:700;width:160px;">Report Type</td><td style="padding:8px 6px;">${payload.reportType}</td></tr>
            <tr><td style="padding:8px 6px;color:#64748b;font-weight:700;">Start Date</td><td style="padding:8px 6px;">${payload.startDate}</td></tr>
            <tr><td style="padding:8px 6px;color:#64748b;font-weight:700;">End Date</td><td style="padding:8px 6px;">${payload.endDate}</td></tr>
            <tr><td style="padding:8px 6px;color:#64748b;font-weight:700;">Detail Mode</td><td style="padding:8px 6px;">${payload.detailMode}</td></tr>
            <tr><td style="padding:8px 6px;color:#64748b;font-weight:700;">Format</td><td style="padding:8px 6px;">${String(payload.format || "").toUpperCase()}</td></tr>
            <tr><td style="padding:8px 6px;color:#64748b;font-weight:700;">Column</td><td style="padding:8px 6px;">${payload.column || "All"}</td></tr>
          </table>
          <p style="margin:14px 0 0;font-size:12px;color:#94a3b8;">Generated by CAPSTONE Admin Dashboard</p>
        </div>
      </div>
    </div>
  `;

  try {
    await transporter.sendMail({
      from: smtpFrom,
      to: payload.to,
      subject,
      text: textBody,
      html: htmlBody,
      attachments: [
        {
          filename: payload.attachment.fileName,
          content: decodeBase64ToBytes(payload.attachment.contentBase64),
          contentType: payload.attachment.mimeType,
        },
      ],
    });

    return new Response(JSON.stringify({ ok: true }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error) {
    return badRequest(
      `SMTP send failed: ${error instanceof Error ? error.message : "Unknown error"}`,
      500
    );
  }
});
